create table tickets (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    description varchar(5000) not null,
    priority varchar(16) not null,
    status varchar(16) not null,
    assignee varchar(100),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_tickets_queue on tickets (updated_at desc, id desc);

create table comments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null references tickets (id),
    author_name varchar(100) not null,
    body varchar(2000) not null,
    created_at timestamp with time zone not null
);

create index idx_comments_ticket on comments (ticket_id, created_at, id);
